### ISSUE TITLE
Entity Relationship Diagram

### ISSUE THREAD

**Issue by Philippoes** [CraftAcademy/slow_food_sinatra_nov#14]
![slow_food_sinatra_nov_v1](https://cloud.githubusercontent.com/assets/22058587/20714556/a4bdbd2c-b64c-11e6-9d9f-12ccb4234324.png)

https://editor.ponyorm.com/user/Philippoes/slow_food_sinatra_nov

**Comment by rmzse** [comment]
@AmberWilkie can u pls check our first ER model? we made it with MVP in mind, we just want to be able to create an order

**Comment by AmberWilkie** [comment]
One of the requirements of the project is that users must register before they can check out. I don’t see that represented on the ERD

**Comment by rmzse** [comment]
@AmberWilkie That's true, we figured that in order to make the minimum product that actually works we would prioritize what would get us there, so we will included in later versions

**Comment by AmberWilkie** [comment]
Your MVP should include all the requirements we have given you. That is what the "client" has requested. You may not know how to get there yet, but that's ok. Things that you feel are less important can go to the end of the backlog, but should not be left out entirely.

**Comment by rmzse** [comment]
Are you sure abt that?

If so, does it mean that we should prioritize some stuff over others when building the code then? Or at what point in our process do you say we should make this sort of priorities?

**Comment by rmzse** [comment]
@AmberWilkie I am asking because @tochman encouraged us to think even more MVP when prioritizing. Perhaps we understood him wrong?

**Comment by AmberWilkie** [comment]
You need to prioritize as soon as you start work. That is how you know what to build next. Your backlog should be ordered by what needs to come first in order to complete the assignment. But eventually you will be able to choose - should I work on categories or user registration? And you can prioritize based on whatever you like.

**Comment by rmzse** [comment]
Hm, I'm a little confused now – phaps we can address this in the next scrum? :)

**Comment by AmberWilkie** [comment]
Your design sprint should include everything you want to get done during this week (this sprint, or period of coding). You may not complete everything, and that's ok, but you want to plan out next steps now, while you're thinking big-picture.
You are working towards an MVP. You won't have one until you complete all the requirements we've given you. But you also want to build your project so that you are making the changes that will be most important to the customer first. So if we ask to see a demo tomorrow, you will have something to show. Then more on Thursday, more on Friday, etc. That's what Thomas means by working towards an MVP. You do the most important thing first so you can show the client as early as possible. That does *not* mean you have an MVP yet.
